from __future__ import annotations

from mlx_ui import engine_resolution as _engine_resolution
from mlx_ui import runtime_metadata as _runtime_metadata
from mlx_ui import settings_schema as _settings_schema
from mlx_ui import settings_store as _settings_store

# Compatibility re-exports: schema + persistence.
CONFIGURABLE_ENGINE_CHOICES = _settings_schema.CONFIGURABLE_ENGINE_CHOICES
normalize_log_level = _settings_schema.normalize_log_level
validate_settings_payload = _settings_schema.validate_settings_payload
compute_effective_settings = _settings_store.compute_effective_settings
get_settings_path = _settings_store.get_settings_path
read_settings_file = _settings_store.read_settings_file
update_settings_file = _settings_store.update_settings_file
write_settings_file = _settings_store.write_settings_file

# Compatibility re-exports: runtime metadata snapshots.
PARAKEET_LIVE_BETA_ENV = _runtime_metadata.PARAKEET_LIVE_BETA_ENV
PARAKEET_LIVE_LEFT_CONTEXT_SECS = _runtime_metadata.PARAKEET_LIVE_LEFT_CONTEXT_SECS
PARAKEET_LIVE_CHUNK_SECS = _runtime_metadata.PARAKEET_LIVE_CHUNK_SECS
PARAKEET_LIVE_RIGHT_CONTEXT_SECS = _runtime_metadata.PARAKEET_LIVE_RIGHT_CONTEXT_SECS
PARAKEET_LIVE_TIMESLICE_MS = _runtime_metadata.PARAKEET_LIVE_TIMESLICE_MS
build_settings_snapshot = _runtime_metadata.build_settings_snapshot
build_telegram_snapshot = _runtime_metadata.build_telegram_snapshot
build_cohere_snapshot = _runtime_metadata.build_cohere_snapshot
build_local_model_visibility = _runtime_metadata.build_local_model_visibility
build_live_transcription_snapshot = _runtime_metadata.build_live_transcription_snapshot
build_runtime_metadata = _runtime_metadata.build_runtime_metadata
list_downloaded_models = _runtime_metadata.list_downloaded_models
list_whisper_models = _runtime_metadata.list_whisper_models
list_parakeet_models = _runtime_metadata.list_parakeet_models
read_build_date = _runtime_metadata.read_build_date
is_whisper_available = _runtime_metadata.is_whisper_available
is_wtm_available = _runtime_metadata.is_wtm_available
is_cohere_available = _runtime_metadata.is_cohere_available

# Compatibility re-exports: engine resolution / transcriber selection.
ResolvedTranscriberSettings = _engine_resolution.ResolvedTranscriberSettings
resolve_requested_engine_with_settings = (
    _engine_resolution.resolve_requested_engine_with_settings
)
resolve_default_language_with_settings = (
    _engine_resolution.resolve_default_language_with_settings
)
resolve_job_transcriber_spec_with_settings = (
    _engine_resolution.resolve_job_transcriber_spec_with_settings
)
resolve_transcriber_with_settings = _engine_resolution.resolve_transcriber_with_settings
